// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs convert-timestamp`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "convert-color",
    "icon": "🎨",
    "name": {
      "en": "Convert Color",
      "ja": "カラー変換",
      "zh": "颜色转换",
      "de": "Farbe umwandeln",
      "es": "Convertir color"
    },
    "desc": {
      "en": "Convert live between HEX, RGB and HSL with a preview swatch.",
      "ja": "HEX・RGB・HSLをリアルタイム相互変換。プレビュー付き。",
      "zh": "在 HEX、RGB 和 HSL 之间实时转换，附带预览色块。",
      "de": "Live-Umwandlung zwischen HEX, RGB und HSL mit Vorschau.",
      "es": "Convierte en vivo entre HEX, RGB y HSL con una vista previa."
    }
  },
  {
    "slug": "format-json",
    "icon": "📐",
    "name": {
      "en": "Format JSON",
      "ja": "JSON整形",
      "zh": "格式化 JSON",
      "de": "JSON formatieren",
      "es": "Formatear JSON"
    },
    "desc": {
      "en": "Pretty-print, validate, or minify JSON.",
      "ja": "JSONを整形・検証・圧縮。",
      "zh": "美化打印、校验或压缩 JSON。",
      "de": "JSON formatieren, validieren oder minimieren.",
      "es": "Formatea, valida o minifica JSON."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'convert-timestamp';
